### ISSUE TITLE
Discussion on scalability

### ISSUE THREAD

**Issue by yansheng105** [erdemcer/kafka-connect-oracle#92]
Hi erdemcer!

I noticed that only one oracle server seems to be configured in the OracleSourceConnector.properties file.
Can you consider using the configuration file in Yaml format to enable the connector to monitor multiple oracle servers at the same time? Perhaps you can also add the configuration file dynamic loading function so that you do not need to restart the connector after adding tables that need to be synchronized.

Thanks.

**Comment by yansheng105** [comment]
A possible configuration file format is as follows:
```
name: oracle-logminer-connector
connector:
  class: com.ecer.kafka.connect.oracle.OracleSourceConnector
srcDataSources:
- instance: demo1
  database:
    name: orcl
    alias: oracle
    hostname: 192.168.40.12
    port: 1521
    user: kminer
    password: kminerpass
    fetch:
      size: 1
    table:
      whitelist: TEST.*
      blacklist:
    parse:
      dml:
        data: true
    reset:
      offset: true
    start:
      scn:
    multitenant: false
    tasks:
      max: 1
    topic: cdctest
    dml:
      types:
- instance: demo2
  database:
    name: orcl
    alias: oracle
    hostname: 192.168.40.13
    port: 1521
    user: kminer
    password: kminerpass
    fetch:
      size: 1
    table:
      whitelist: TEST.*
      blacklist:
    parse:
      dml:
        data: true
    reset:
      offset: true
    start:
      scn:
    multitenant: false
    tasks:
      max: 1
    topic: cdctest
    dml:
      types:
```
